### ISSUE TITLE
Plugin bug?

### ISSUE THREAD

**Issue by BartosB13** [Tweetzy/Markets#94]
Hello! Is this caused by a plugin or something on my end? I even did a fresh install of the plugin but it didn't help.

```
[14:51:23 INFO]: Bartos13 issued server command: /markets
[14:51:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'markets' in plugin Markets v2.17.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-497]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Unable to set profile com.mojang.authlib.GameProfile@107a53e4[id=6d3e065d-b341-380b-8dc2-e2107a683d2e,name=XSeries,properties={XSeries=[Property[name=XSeries, value=true, signature=null]], textures=[Property[name=textures, value=eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmMxZTczMDIzMzUyY2JjNzdiODk2ZmU3ZWEyNDJiNDMxNDNlMDEzYmVjNWJmMzE0ZDQxZTVmMjY1NDhmYjJkMiJ9fX0=, signature=null]]}] to SKULL_META:{meta-type=SKULL}
        at ca.tweetzy.markets.flight.utils.profiles.objects.ProfileContainer$ItemMetaProfileContainer.setProfile(ProfileContainer.java:64) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.utils.profiles.builder.ProfileInstruction.apply(ProfileInstruction.java:160) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.utils.QuickItem.createTexturedHead(QuickItem.java:453) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.config.ConfigEntry.getItemStackOr(ConfigEntry.java:221) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.config.ConfigEntry.getItemStack(ConfigEntry.java:210) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.gui.shared.MarketsMainGUI.draw(MarketsMainGUI.java:38) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.gui.shared.MarketsMainGUI.<init>(MarketsMainGUI.java:28) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.commands.MarketsCommand.execute(MarketsCommand.java:31) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.command.CommandManager.processRequirements(CommandManager.java:331) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.command.CommandManager.onCommand(CommandManager.java:231) ~[Markets v2.17.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class ca.tweetzy.markets.flight.utils.profiles.ProfilesCore
        at ca.tweetzy.markets.flight.utils.profiles.objects.ProfileContainer$ItemMetaProfileContainer.setProfile(ProfileContainer.java:62) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.utils.profiles.builder.ProfileInstruction.apply(ProfileInstruction.java:160) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.utils.QuickItem.createTexturedHead(QuickItem.java:453) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.config.ConfigEntry.getItemStackOr(ConfigEntry.java:221) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.config.ConfigEntry.getItemStack(ConfigEntry.java:210) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.gui.shared.MarketsMainGUI.draw(MarketsMainGUI.java:38) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.gui.shared.MarketsMainGUI.<init>(MarketsMainGUI.java:28) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.commands.MarketsCommand.execute(MarketsCommand.java:31) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.command.CommandManager.processRequirements(CommandManager.java:331) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.command.CommandManager.onCommand(CommandManager.java:231) ~[Markets v2.17.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldException: None of the fields were found for FieldMemberHandle{protected/private final Proxy h/proxy} [in thread "Server thread"]
        at ca.tweetzy.markets.flight.utils.reflection.jvm.FieldMemberHandle.reflectJvm(FieldMemberHandle.java:175) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.utils.reflection.jvm.FieldMemberHandle.reflect(FieldMemberHandle.java:109) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.utils.reflection.jvm.FieldMemberHandle.reflect(FieldMemberHandle.java:19) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.utils.reflection.Handle.unreflect(Handle.java:24) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.utils.profiles.ProfilesCore.<clinit>(ProfilesCore.java:132) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.utils.profiles.objects.ProfileContainer$ItemMetaProfileContainer.setProfile(ProfileContainer.java:62) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.utils.profiles.builder.ProfileInstruction.apply(ProfileInstruction.java:160) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.utils.QuickItem.createTexturedHead(QuickItem.java:453) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.config.ConfigEntry.getItemStackOr(ConfigEntry.java:221) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.config.ConfigEntry.getItemStack(ConfigEntry.java:210) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.gui.shared.MarketsMainGUI.draw(MarketsMainGUI.java:38) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.gui.shared.MarketsMainGUI.<init>(MarketsMainGUI.java:28) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.commands.MarketsCommand.execute(MarketsCommand.java:31) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.command.CommandManager.processRequirements(CommandManager.java:331) ~[Markets v2.17.4.jar:?]
        at ca.tweetzy.markets.flight.command.CommandManager.onCommand(CommandManager.java:231) ~[Markets v2.17.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more
```

**Comment by BartosB13** [comment]
The plugin also does not create a language file.

![image](https://github.com/user-attachments/assets/22c42120-b035-4c7d-a6a4-6095f4525ec2)

**Comment by kiranhart** [comment]
There's a temporary jar posted in the markets support channel on the server that fixes these two things

**Comment by BartosB13** [comment]
ok thanks

**Comment by BartosB13** [comment]
A little note. In version 2.18 the basic command now works, but the default language file still isn't generated.

**Comment by BartosB13** [comment]
Language files are already being generated.

I have the impression that the `/markets reload` command doesn't work. After using it (I think) nothing happens. There is definitely no message.

Plus a small question. Can your plugins (Markets and Auction House) receive an option to add additional aliases in the config? Is it feasible? If so, I can create separate issues threads about this.

**Comment by kiranhart** [comment]
> Language files are already being generated.
> 
> I have the impression that the /markets reload command does not work completely correctly. There is definitely no message. Plus I am not sure anymore, but I think the plugin crashed when I changed the language file in config and did a reload.
> 
> Plus a small question. Can your plugins (Markets and Auction House) receive an option to add additional aliases in the config? Is it feasible? If so, I can create separate issues threads about this.

The reload command does reload the translations/config. there just isnt any message.
Also what do you mean by additional aliases? But yea just make new suggestion issue for whatever to keep it organized
